### ISSUE TITLE
Brandons twitter name not appearing

### ISSUE THREAD

**Issue by Rushfriend** [dutchtalk/LMGAccounts#4]
Hi there,

I think I have found an issue with the site. At Brandons Twitter button/link his account name isn't appearing although the link works just fine.

![Screenshot](https://rushfriend.files.wordpress.com/2016/07/github-issue-lmgaccounts.png)

I have looked in the code real quick and there his twitter username is present on the desired location.

``` html
<div id="brandon">
        <a class="card brandon employee namecard">
          <p class="employee name">Brandon</p>
        </a>
        <a class="card twitter" href="https://twitter.com/Brandon_Y_Lee">
          <img class="twitter socialimg" src="images/twitterlogo.svg"></img>
          <p class="socialname twitter">@Brandon_Y_Lee</p>
        </a>
```

Hope you/someone will be able to fix the problem.

Regards, Rushfriend

**Comment by mikaturk** [comment]
hmm yeah ill be looking into that, i've seen this problem before in development and it's because the textbox is too small :)

edit: it looks fine to me?
can you provide details like OS, Browser and Browser version?
I'm using OSX 10.10 and i tested chrome 51, firefox 47 and safari 9

**Comment by mikaturk** [comment]
I found the same issue on my windows 10 machine with chrome 53, so upping the size of the cards :)

It should be fixed now 👍 
Fix: https://github.com/dutchtalk/lmgaccounts/commit/1f97410486a87a67b76944f418ebcfcb87e13fc2
